const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs'), path = require('node:path');
const base = process.env.BASE_URL || 'http://127.0.0.1:3000';
const output = process.env.BROWSER_ARTIFACT_DIR || '/private/tmp/umbrella-scene-browser';
fs.mkdirSync(output,{recursive:true});
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.waitForSelector('#intro',{state:'hidden'});await page.waitForFunction(()=>!document.getElementById('send').disabled);
  if(await page.locator('.chat-list').count())throw Error('character chat UX still exists');
  if(await page.locator('.environment').count()!==1)throw Error('scene description missing');
  if(await page.locator('.action').count()!==2)throw Error('stage directions missing');
  if(await page.locator('.dialogue').count()!==1)throw Error('opening dialogue missing');
  await page.waitForTimeout(400);
  await page.screenshot({path:path.join(output,'desktop-scene.png')});
  await page.locator('#input').fill('Мой свободный текст. Только я решаю.');await page.getByRole('button',{name:'Продолжить историю',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('send').disabled);
  const player=await page.locator('.player .event-text').allTextContents();
  if(JSON.stringify(player)!==JSON.stringify(['Мой свободный текст. Только я решаю.']))throw Error('player text changed');
  await page.reload();await page.waitForFunction(()=>!document.getElementById('send').disabled);if(await page.locator('.player').count()!==1)throw Error('reload lost turn');
  await page.waitForTimeout(1600);
  await page.locator('#input').fill('Беру фотографию. Прячу фотографию за спину. Ухожу.');await page.getByRole('button',{name:'Продолжить историю',exact:true}).click();await page.waitForFunction(()=>!document.getElementById('send').disabled);
  if(!await page.locator('#location').textContent().then(t=>t.includes('коридор')))throw Error('player move failed');
  if(!await page.locator('#inventory').textContent().then(t=>t.includes('фотография')))throw Error('inventory failed');
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3});mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto(base);await mobile.waitForFunction(()=>!document.getElementById('send').disabled);
  await mobile.waitForTimeout(400);
  await mobile.screenshot({path:path.join(output,'mobile-scene.png')});
  const measure=await mobile.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:innerHeight,input:document.getElementById('input').getBoundingClientRect().toJSON(),serviceWorker:!!navigator.serviceWorker.controller}));
  if(measure.scrollWidth>measure.width)throw Error('horizontal overflow');
  await mobile.getByRole('button',{name:'Показать состояние сцены'}).click();if(!await mobile.locator('#scene-panel').evaluate(e=>e.classList.contains('open')))throw Error('scene panel failed');
  await mobile.getByRole('button',{name:'Показать состояние сцены'}).click();
  await mobile.setViewportSize({width:390,height:460});await mobile.locator('#input').fill('Черновик моих действий');await mobile.screenshot({path:path.join(output,'mobile-keyboard.png')});
  const keyboard=await mobile.locator('#input').boundingBox();if(keyboard.y+keyboard.height>460)throw Error('input hidden');
  await mobile.reload();await mobile.waitForFunction(()=>!document.getElementById('send').disabled);if(await mobile.locator('#input').inputValue()!=='Черновик моих действий')throw Error('draft lost');
  await mobile.context().setOffline(true);await mobile.reload();await mobile.waitForTimeout(500);if(!await mobile.locator('.environment').count())throw Error('offline scene lost');
  if(await mobile.locator('#input').inputValue()!=='Черновик моих действий')throw Error('offline draft lost');
  if(errors.length)throw Error(JSON.stringify(errors));
  console.log(JSON.stringify({player,measure,keyboard,errors,sceneMove:true,inventory:true,reload:true,draft:true,offlineShell:true}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
